# Generated by Django 5.1.1 on 2024-12-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionModel',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.datetimemodel')),
                ('article_id', models.IntegerField()),
                ('intrant_id', models.IntegerField()),
                ('user_applyed', models.CharField(max_length=50)),
            ],
            bases=('base.datetimemodel',),
        ),
    ]
