# Generated by Django 5.1.1 on 2024-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_productionmodel_user_applyed'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmodel',
            name='user_applyed',
            field=models.ManyToManyField(to='users.usermodel'),
        ),
    ]
