# Generated by Django 5.1.1 on 2024-12-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('labelledmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.labelledmodel')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('selled', models.IntegerField()),
                ('disponible', models.IntegerField()),
            ],
            bases=('base.labelledmodel',),
        ),
        migrations.CreateModel(
            name='IntrantModel',
            fields=[
                ('labelledmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.labelledmodel')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('used', models.IntegerField()),
                ('disponible', models.IntegerField()),
            ],
            bases=('base.labelledmodel',),
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('labelledmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.labelledmodel')),
                ('category', models.CharField(max_length=255)),
            ],
            bases=('base.labelledmodel',),
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('namedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.namedmodel')),
                ('first_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
            ],
            bases=('base.namedmodel',),
        ),
    ]
