# Generated by Django 5.1.1 on 2024-12-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('labelledmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.labelledmodel')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('selled', models.IntegerField()),
                ('disponible', models.IntegerField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.providermodel')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.producttypemodel')),
            ],
            bases=('base.labelledmodel',),
        ),
    ]
